### ISSUE TITLE
Top Menu strony

### ISSUE THREAD

**Issue by rekah4** [marcin3412/lotek#4]
Utworzyć top menu dla zalogowanych i nie zalogowanych użytkowników.
W menu powinny znaleźć się następujące odnośniki:
- Strona główna
- zalogowany jako:
- edycja profilu
- podgląd profilu
- zmiana emailu
- zmiana hasła
- moje saldo
- statystyki
- moje ostatnie wygrane
- kumulacja
- historia kumulacji

Mile widziane dalsze sugestie 
W tym zadaniu menu nie przenosi na inne strony

**Comment by marcin3412** [comment]
Dodałbym jeszcze jakąś wyszukiwarkę np. Userów, ticketów po numerze itd. itp.

**Comment by rekah4** [comment]
Jak najbardziej, może użytkowników nie bo to taka inwigilacja, ale co do ticketów jak najbardziej
